### ISSUE TITLE
Clean-up the codebase

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#119]
### Why?
The API has changed rapidly. It's time to readjust and restructure some things so that they are more clear and read better.

### TODO
- [x] Rename `BigNum` to `CurveBN`
~Rename `Point` to `CurvePoint`~
- [x] Build helper utilities for OpenSSL functions
- [x] Cleanup random oracle functions
- [x] Come up with a solution for many class dependent `to_bytes` and `from_bytes` methods.

**Comment by tuxxy** [comment]
Unsure if we're continuing on with renaming `Point` to `CurvePoint`.

I really like the uniform nature of having a `CurveBN` and ` CurvePoint`, but it seems a bit awkard.

**Comment by jMyles** [comment]
I don't really know what "Curve" adds to Point - will we ever care to have a parent class to describe a `Point` that *isn't* on a curve?  Won't `Points` always know which curve they're on?

If the answer is "no," then sure, `CurvePoint` (or better IMO, `PointOnCurve`) makes sense.

**Comment by KPrasch** [comment]
Lets move this to a more specific Issue if there is still anything outstanding discussion.
